global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
          - "localhost:9090"

  - job_name: "ec2_vm"
    static_configs:
      - targets:
          - "3.70.39.129:9100"
